### ISSUE TITLE
No LSB/USB single sideband tx on Rpitx + csdr

### ISSUE THREAD

**Issue by CHMCuba93** [F5OEO/rpitx#107]
After several tests with the software I have transmitted AM / FM with Rpitx + CSDR using a microphone input but not USB / LSB (SSB) modes. When trying to transmit USB / LSB, nothing is heard, no RF signal and in some cases only one powerful carrier at the center frequency. Could it be libraries problem (CSDR libraries?) or other needed software updates? thanks for answers.
Carlos Hernandez Morales CL6CHM
Cuba

**Comment by F5OEO** [comment]
See testssb.sh on version 2.

**Comment by kukutt** [comment]
Is testssb.sh transmitted  usb?
How to transmitted lsb?
