### ISSUE TITLE
Question: How to set AM frequency

### ISSUE THREAD

**Issue by xMateMCPE** [F5OEO/rpitx#110]
So there is this code from testam.sh:
```
./piam sampleaudio.wav am.rfa
sudo ./rpitx -m RFA -i am.rfa -f 433900 -l
```
I want to broadcast on 1251 kHz
What do i need to replace 433900 with? I tried with 1251 but nothing happens.
Any help would be appreciated, im still new to frequencies and Linux

**Comment by gfdfdxc** [comment]
Check the GPIO:GPIO_18 pin 12

**Comment by F5OEO** [comment]
Fixed in version 2
