### ISSUE TITLE
Bad quality, suggestions?

### ISSUE THREAD

**Issue by acujl** [F5OEO/rpitx#111]
Heya! I'm transmitting on 88Mhz but the audio is really bad quality, I have an antena (copper wire soldered) on the pin. Any suggestions?
Even without the homemade antena the audio is crap
I normaly do:
rpitx  -i /home/pi/SDRSharp_20180924_181735Z_AF.wav -f 88000

**Comment by moliata** [comment]
First, try using a 10cm jumper wire instead and make sure, you are connecting it to a correct pin, that may help. Then try to increase the frequency to around 100MHz, a couple of MHz down or up. Last of all, try to use a different radio receiver, like a RTL-SDR (if you don't use it already).

**Comment by acujl** [comment]
Thanks for the suggestions! Yes, I already use RTL-SDR 👍

**Comment by F5OEO** [comment]
Fixed on version 2
