### ISSUE TITLE
PSK with gnuradio and rpitx

### ISSUE THREAD

**Issue by goulum29** [F5OEO/rpitx#112]
Hi, i'm trying to send a simple text file via PSK modulation by using gnuRadio and rpitx. I modulate with gnu radio and send via tcp socket to rpitx listening on tcp : 

` nc -l 9999 | sudo rpitx -i- -m IQFLOAT -f 67000`

The modulator : 

![image](https://user-images.githubusercontent.com/44431383/47424364-cc1fe800-d787-11e8-984f-f01ccbfea409.png)

And i demodulate via gnu-radio by using rtl sdr.

![image](https://user-images.githubusercontent.com/44431383/47424744-afd07b00-d788-11e8-8da7-748dfd36ea6d.png)

I launch all these process and i revceive nothing,my ouptut file still at 0 bit , i can see on the spectrum and the waterfall that is a modulation but on the eye diagramm, i see that :

![capture d ecran du 2018-10-24 12-43-50](https://user-images.githubusercontent.com/44431383/47425793-b8768080-d78b-11e8-90ed-4ecd40f178f8.png)

![capture d ecran du 2018-10-24 12-44-34](https://user-images.githubusercontent.com/44431383/47425806-c2987f00-d78b-11e8-8507-5fa3b9584884.png)

I try some different configuration about filtering and i get sometimes better constellation, but still transmit nothing. Sometimes, i have the "circle" of psk modulation but i clearly put in parameters 2 constellations point...
It's for personnal testing, i'm just trying to have a simple and functionnal digital modulation.

If i was wrong somewhere, if you have any idea ?  I take any advice, thank you in advance.

**Comment by ha7ilm** [comment]
First could also try first putting together a simulation in a single flowgraph that contains both the `PSK Mod` and the `PSK Demod` blocks, and a channel model block between them, with some frequency offset and additive noise. That would allow you to make sure that the whole thing is likely to work with a pair of real SDRs.

Also make sure that the amplitude of the I/Q signal you're sending into RPiTX is correct. 

As a note, for PSK and FSK I'd rather use the `-m RF` mode instead, as without PWM it's likely that you'll get a cleaner signal. For PSK that requires some preprocessing though, so you won't be able to use the `PSK Mod` block then.

**Comment by goulum29** [comment]
Ok , I will try that, but wich amplitude it's correct ? Amplitude it's not set by the carrier ?

**Comment by ha7ilm** [comment]
Maybe it's correct if the signal uses the range between `+1.0` and `-1.0` (for both I and Q), but check the `rpitx` code / documentation.

**Comment by F5OEO** [comment]
Be sure to set you samplerate to 48000 which is the default (from my memory). However, this branch is end of life and the new v2beta branch will be released soon. It is based on librpitx which has already some easy class to make FSK and PSK natively.

**Comment by goulum29** [comment]
Ok, i will try all your advice and send you my return. And try FSK (gaussian) modulation.

**Comment by goulum29** [comment]
I have test your proposal ha7ilm with channelizer, full software mod-demod with adding noise. It's work but when the noise rise up the signal seems pretty clear but 0 bit passed.
However i'm sorry but i don't understand wich parameters i need to pass to my flow graph and rpitx....
For me the IQFLOAT parameters accepts the complex output of gnuRadio. And i check my amplitude after modulation it's -1 and 1. 
I try with a 48k sample rate on my rtl-sdr source, i try band pass filter, but still not clear.
All my mod-demod works on software, with adding some noise but when passing to rpitx it's doesn't work.... I think i miss something

Thanks in advance

**Comment by F5OEO** [comment]
For PSK , prefere to use MPSK modulator in V2 instead of using i/Q.
