### ISSUE TITLE
Crashes on PI zero W after transmission : (ssh over Wifi)

### ISSUE THREAD

**Issue by clemibunge** [F5OEO/rpitx#116]

**Comment by clemibunge** [comment]
PI zero stops responding

**Comment by F5OEO** [comment]
Do you use Wifi on PizeroW ? Crash after transmission, means that transmission have succeed ? Which mode did you use (tune, chirp, ssb ?)

**Comment by F5OEO** [comment]
OK, this is a Wifi issue I need to fix. All tests are done using ethernet connexion right now.

**Comment by F5OEO** [comment]
Same as https://github.com/F5OEO/rpitx/issues/122.
