### ISSUE TITLE
Question about POCSAG

### ISSUE THREAD

**Issue by Tim30021** [F5OEO/rpitx#121]
Hello,

today i tried to transmit some POCSAG-Data to my Pager. I noticed, that it is no possible to change the function bit. It is always "3". Can you explain me please how to change the function bit?

I modified the testpocsag.sh file like this to do some tests.

echo -e "0236799: Hello world. Testmessage!" | sudo ./pocsag -f 434.000e6

This is the decoded message:

0236794 3 (Alpha) Hello world. Testmessage!

The Adress i typed in was 0236799 an the decoded adress is 0236794. How can i calculate the right adress i should type in?

Greetings!

**Comment by F5OEO** [comment]
This code is a fork ...I checked quickly that I can receive a pocsag message.
 Effectively the sourcecode  seems to fix type and make address modulo 8 (can be modified to be variable) : 
https://github.com/F5OEO/rpitx/blob/9c2ef5e5f0289c03fab25bb9174e97649c700421/src/pocsag/pocsag.cpp#L272

Need to check more deeply pocsag protocol to fix.

**Comment by pyrog** [comment]
Hi,

Function bits are set to **3** to send "alpha-numeric" messages according to [RECOMMENDATION ITU-R M.584-2](https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.584-2-199711-I!!PDF-E.pdf).

For "numeric only" messages, functions bits are set to **0**.

Functions bits **1** or **2** are usually used to "ring only" the pager (but in practice, the behaviour depends on the settings of the transmitter/pager).

The functions bits are "hard coded" in [pocsag.cpp#L74](https://github.com/F5OEO/rpitx/blob/master/src/pocsag/pocsag.cpp#L74).

**Comment by pyrog** [comment]
Function bits could be changed. See #144

**Comment by pyrog** [comment]
The format is `address:message` where address is the **RIC** or **CAPCODE**.
0 ≤ RIC ≤ 2097151
It could be followed by a letter (A,B,C or D) witch is the function bits (0,1,2 or 3).


Assuming that 0705967 is your pager address, following examples should work:
```bash
printf "0705967:Helloworld" | sudo ./pocsag -f "160600000" -r 512
```
```bash
printf "705967:Helloworld" | sudo ./pocsag -f "160600000" -r 512
```
```bash
printf "705967D:Helloworld" | sudo ./pocsag -f "160600000" -r 512
```

**Comment by Povezi** [comment]
I checked, I have compiled latest version with [(address & 0x7)](https://github.com/pyrog/rpitx/commit/c7705fa5fabb981fddfbaaed46ec31986b77a99b) 

so this bug is fixed?

will try to add echo at the end after e.g.: PCM clk=4086 / 145
