### ISSUE TITLE
How to stop transmission?

### ISSUE THREAD

**Issue by maxlock** [F5OEO/rpitx#123]
Hi, how do I stop or exit rpitx once it's finished transmitting the content of a file? I am generating wav files containing aprs packets. I would like to transmit these once then stop.

Thanks for the truely awesome software too, very very much appreciated :)

**Comment by maxlock** [comment]
FYI I'm running raspbian on an original pi zero, no wireless, connected via usb cable.

**Comment by F5OEO** [comment]
APRS should surely beeing modulated in NFM afterwards. Think that you have use the method in testnfm.sh. Just ctl^c when you want to stop. By default it loops, but you can modify script to transmit only once.

**Comment by maxlock** [comment]
Yes, that's what I'm doing. The wav file is only a couple of seconds long. Here's a sample, I had to stop rpitx after a while

```
pi@raspberrypi:~/rpitx $ aprs -c NOCALL -o wibble.wav "testtext"
pi@raspberrypi:~/rpitx $ cat wibble.wav | csdr convert_i16_f | csdr gain_ff 7000 | csdr convert_f_samplerf 20833 > pitxfile
pi@raspberrypi:~/rpitx $ time sudo ./rpitx -i ./pitxfile -m RF -f 434000
Warning : rpitx V2 is only to try to be compatible with version 1
Channel 14 CBSize 32000 UsermemSize 16000
Using mbox device /dev/vcio.
1088000 Size NUM PAGES 266 PAGE_SIZE 4096
BufferSize 16000 , cb 32000 user 16000
Warning: NTP calibrate failed
Warning: NTP calibrate failed
Warning: NTP calibrate failed
Freq = 867999993
 multiplier:45.208333 divider:2 VCO: 868.0MHz Spurious 0.000000 
Master PLLC Locked
Clk Number 5 div 2 frac 0
Freq = 500000006
PCM prediv = 10
PCM clk=1041 / 2730
^CCaught signal - Terminating 2

real	0m36.559s
user	0m14.159s
sys	0m19.514s
```

**Comment by maxlock** [comment]
pi@raspberrypi:~/rpitx $ sox ./wibble.wav -n stat
Samples read:            140532
Length (seconds):      3.186667
Scaled by:         2147483647.0
Maximum amplitude:     0.499969
Minimum amplitude:    -0.500000
Midline amplitude:    -0.000015
Mean    norm:          0.108565
Mean    amplitude:     0.000013
RMS     amplitude:     0.206448
Maximum delta:         0.429382
Minimum delta:         0.000000
Mean    delta:         0.029692
RMS     delta:         0.057973
Rough   frequency:         1970
Volume adjustment:        2.000

**Comment by F5OEO** [comment]
Thx for pointing the issue. Just commit a potential fix. Can you confirm it works now?

**Comment by maxlock** [comment]
awesome! will do....
