### ISSUE TITLE
AF shift issue.

### ISSUE THREAD

**Issue by maxlock** [F5OEO/rpitx#125]
I'm generating a 1khz tone using sox
```
sox -V -r 48000 -n -b 16 -c 2 note.wav synth 15 sin 1000
```
then converting for rpitx
```
cat note.wav | csdr convert_i16_f | csdr gain_ff 7000 | csdr convert_f_samplerf 20833 > note_processed.wav
```
and finally transmitting 
```
sudo rpitx -i ./note_processed.wav -m RF -f 434000
```

The received tone is shifted down to 500hz, with additional harmonics at 1khz,1.5khz & 2khz etc. I noticed this because my generated aprs packets sounded off, and aren't being decoded properly. Is there anything that could cause a tone shift happening? if I play back the 1khz wav locally it's fine, and there are no harmonics either.

I've also sent the sampleaudio.wav and it sounds ok to me. is there additionally something I could change in the csdr conversion?

I'm using a USB attached original pi zero and version 2.0

Thanks, Max. G7UOZ.

**Comment by F5OEO** [comment]
Interesting question : first , you should use a mono file : 
`sox -V -r 48000 -n -b 16 -c 1 note.wav synth 15 sin 1000`

As per https://en.wikipedia.org/wiki/Frequency_modulation, see Bessels functions . Here modulation deviation is 7khz and modulation frequency is 1khz, means a modulation index of 7. Spectrum seems to correspond to theory ?

**Comment by maxlock** [comment]
Interesting indeed, when running with a single channel wav, everything is fine. I'll keep digging and thanks for the bessels function link, good reading :)

**Comment by maxlock** [comment]
ok, so it seems that the source wav must have a 48khz rate, the following will generate two 1khz tones but will  be pitch shifted when transmitted.

```
sox -V -r 44000 -n -b 16 -c 1 note44.wav synth 15 sin 1000
sox -V -r 48000 -n -b 16 -c 1 note48.wav synth 15 sin 1000

cat note44.wav | csdr convert_i16_f | csdr gain_ff 7000 | csdr convert_f_samplerf 20833 > note44tx.wav
cat note48.wav | csdr convert_i16_f | csdr gain_ff 7000 | csdr convert_f_samplerf 20833 > note48tx.wav

sudo rpitx -i ./note44tx.wav -m RF -f 434000
sudo rpitx -i ./note48tx.wav -m RF -f 434000
```

**Comment by F5OEO** [comment]
You can set the symbolrate with rpitx : -s option (sorry , not in the help of command line)
By default it is 48Khz.

**Comment by maxlock** [comment]
Aha! excellent, thanks again! :)

**Comment by F5OEO** [comment]
Note that csdr convert_f with parameter 20833=1/48000 is not used anymore with version 2.

**Comment by maxlock** [comment]
OK, I was using the test_nfm.sh script (below) as a guide. what would be your suggestion for nbfm then?
```
(while true; do cat sampleaudio.wav; done) | csdr convert_i16_f | csdr gain_ff 7000 | csdr convert_f_samplerf 20833 | sudo ./rpitx -i- -m RF -f $1
```
