### ISSUE TITLE
RPI B+ freezes on transmit

### ISSUE THREAD

**Issue by modezz** [F5OEO/rpitx#127]
clean rasperian install - latest version - also gpu @250 in boot
when starting easytest and try some tansmitting it works for a few seconds then the rpi freezes completly

is this the "partial working" on B+?

thanks

**Comment by F5OEO** [comment]
No partial running is PIB (older model). B+ should work or at least not freeze anything. Need to check again with latest commit and latest Raspbian Lite.

**Comment by modezz** [comment]
oh sorry my fault meant model B !!!

**Comment by F5OEO** [comment]
Ah OK. Yes, only few modes are working? Can't remember exactly? As PI Model B is now quite old, I didn't inspect very deeply thinking that not a lot of people use it.

**Comment by modezz** [comment]
yep - tune seems to work - but all the other modes works too but freeze more or less immediately.... just wanted to know - i will order a new one - thanks!

**Comment by F5OEO** [comment]
Surely a DMA conflict. Have a new one (even a 5$ Pizero) !
