### ISSUE TITLE
Code needs cleanup.

### ISSUE THREAD

**Issue by SopaXorzTaker** [F5OEO/rpitx#15]
I understand that this project is only an experiment, but its code is barely readable.

**Comment by F5OEO** [comment]
Patch is welcome !

**Comment by csete** [comment]
@SopaXorzTaker Not sure why you think the code is barely readable. If it is because of the formatting, there are plenty of freely available tools that can format the code according to your preferred style, e.g. indent, uncrustify and clang-format just to name a few.

**Comment by SopaXorzTaker** [comment]
@csete, I guess that's my fault then. I just have different C code style expectations.

**Comment by SopaXorzTaker** [comment]
Probably worth to run a reformatting tool.
I was talking about some styling issues: e.g. https://github.com/F5OEO/rpitx/blob/master/fm/pifm.c

**Comment by natevw** [comment]
Almost looks like the main thing here might be simply mixed tabs vs. spaces? That might be nice to get cleaned up via a PR as maintainer says.

**Comment by SopaXorzTaker** [comment]
Not only, there also are issues like "int a=5;" (no spaces around), and
there is code that seems dead.
