### ISSUE TITLE
pocsag broken

### ISSUE THREAD

**Issue by F5OEO** [F5OEO/rpitx#151]
Latest commits on librpitx change the way the FSK is working. 

Can you check that it still working (ping to @pyrog )? You need to adjust https://github.com/F5OEO/rpitx/blob/9d26464b728a7ef920c60a0563b8e986e746b734/src/pocsag/pocsag.cpp#L331 with float Deviation=4500*2;

Old version FSK : 0 means -deviation and 1 means +deviation.
New version FSK : 0 means 0, 1 mean +deviation. So central frequency is now F+Deviation/2.

Explantion is that FSK is now mFSK and thus freq=deviation * SymbolValue (0,1..N)

**Comment by pyrog** [comment]
Unfortunately, POCSAG is broken 😔

Tested with all the following values, **multimon-ng detect POCSAG messages**, but TPL and Swissphone **pagers don't**.

```C
float Deviation=4500; 
```
```C
float Deviation=4500*2; 
```
```C
float Deviation=4500/2; 
```

How to be sure that pocsag use the last version of librpitx ?

**Comment by F5OEO** [comment]
Be sure to go rpitx/src/librpitx/src and make
and then make on /rpitx/src , sudo make install.

I need to make a debug message to know which version of librpitx we use.

**Comment by F5OEO** [comment]
Seems to be fixed

**Comment by Povezi** [comment]
yes, pulled lib, make, then make rpitx. tried both without -i and with it. Hackrf detects briefly bar (frequency is good) but didn’t echo address:msg in pocsag receiver
