### ISSUE TITLE
the install script doesn't create a new line

### ISSUE THREAD

**Issue by misaalanshori** [F5OEO/rpitx#153]
![image](https://user-images.githubusercontent.com/38964181/51071936-b84f9800-168b-11e9-8c74-b9068d0b2584.png)
 and it did that, so i was confused why i couldn't connect via the usb cable....
this is on a raspberry pi zero w

**Comment by F5OEO** [comment]
I didn't test with NOOBS (assume we are on Raspbian strecth based).
It seems that you should maybe set gpu_freq=250 in the config.txt which is not located on /boot in NOOBS.

dwc2gpu has no relation with rpitx.

**Comment by dave3825us** [comment]
I am new to linux but got everything installed. But want to know on a pi 3b+, what exactly is rhe gpu and will the fact that this prog changed it, will it affect the pi performance with other programs? Thanks

**Comment by misaalanshori** [comment]
Im not sure what the default value for the gpu_freq is, but if it's a big change it could affect other programs that use the gpu... But rpitx needs to change it to be stable
