### ISSUE TITLE
are there a way to make this work on kali linux?

### ISSUE THREAD

**Issue by misaalanshori** [F5OEO/rpitx#154]
I have installed kali linux on my pi zero w and and it doesnt work. Im not sure what is making it not work. i installed it the way i installed it on raspbian which works fine. 

there were two errors that i noticed when running the install script, and this is one of them:
dvb/dvbs2arm_1v30.S:1798: Error: selected processor does not support `rev r0,r0' in ARM mode
and i think the other one is an error when compiling csdr 

have anyone gotten it working on kali linux?

**Comment by F5OEO** [comment]
Surely some compiler and environment variable to check.

**Comment by MeFisto94** [comment]
related to #173 (at least the csdr issue)

**Comment by F5OEO** [comment]
Fixed now
