### ISSUE TITLE
RX Problem with standard DVB-S receiver.

### ISSUE THREAD

**Issue by virtualrobotix** [F5OEO/rpitx#16]
I try to decode the stream using standard DVB-S receiver ... but when i search the channel the receiver don't found my modulation ... i use the LNA at 9750 I try to check the modulation with HackRF and #SDR amd i see the modulation but i don't have any kind of software for decode DVB-S with HackRF i search online but found nothing ... do you have some suggestions ? If not i order a RTL-SDR ... but i thought that with HackRF i don't need a RTL dongle help me please :) 
Thanks 
Roberto

**Comment by F5OEO** [comment]
Try leandvb which input a pipe in IQ from rtl or HackRF (check if it is int or float32).

**Comment by virtualrobotix** [comment]
Thanks F5OEO do you have some example how i can use HackRF in input as leandvb IQ format to leandvb pipe ? I'm never used it in that way until now.
Thank

**Comment by virtualrobotix** [comment]
But it can work in realtime or only in log data ?

**Comment by SopaXorzTaker** [comment]
It is realtime.

**Comment by F5OEO** [comment]
Closed : relative to rpidatv, not rpitx
