### ISSUE TITLE
Installed latest rpitx and piam execute does not exist?

### ISSUE THREAD

**Issue by dachshund-digital** [F5OEO/rpitx#166]
Installed latest rpitx and piam execute does not exist?

Searched entire file system and find no binary or script file named 'piam' anywhere.  Only found reference to a source code file... piam.c.

Searched all packages available via apt-file command no piam referenced by any package, but clearly it is expected to be part of the rpitx software no?

**Comment by tbird635** [comment]
I have the same problem. Can't convert wav files because there's no PIAM file included.

**Comment by psa-jforestier** [comment]
It seems the PIAM build step in the Makefile has been removed.
Add the following lines in the makefile in src, just before `../rpitx' : 
```
CFLAGS_Piam   = -Wall -g -O2 -Wno-unused-variable
LDFLAGS_Piam  = librpitx/src/librpitx.a -lm -lrt -lpthread -lsndfile -L/opt/vc/lib -lbcm_host
../piam: librpitx/src/librpitx.a
        $(CC) $(CFLAGS_Piam) -o ../piam am/piam.c  $(LDFLAGS_Piam)
```
/!\ Line with $(CC) start with a TAB.

Then, enter `make ../piam` to build the program.

**Comment by PENUT-DEV** [comment]
> It seems the PIAM build step in the Makefile has been removed.
> Add the following lines in the makefile in src, just before `../rpitx' :
> 
> ```
> CFLAGS_Piam   = -Wall -g -O2 -Wno-unused-variable
> LDFLAGS_Piam  = librpitx/src/librpitx.a -lm -lrt -lpthread -lsndfile -L/opt/vc/lib -lbcm_host
> ../piam: librpitx/src/librpitx.a
>         $ (CC) $(CFLAGS_Piam) -o ../piam am/piam.c  $(LDFLAGS_Piam)
> ```
> 
> /!\ Line with $(CC) start with a TAB.
> 
> Then, enter `make ../piam` to build the program.

I've done this one but the result is

Makefile:88: warning: overriding recipe for target '../piam'
Makefile:15: warning: ignoring old recipe for target '../piam'
make: No rule to make target '../am/piam.c', needed by '../piam'. Stop.

**Comment by F5OEO** [comment]
piam is now replaced with csdr / sendiq script. See testpiam.sh

**Comment by Nodi-Rubrum** [comment]
Cool, we test in the next couple days.  Thanks very much for actively supporting RPiTx.
