### ISSUE TITLE
signal is very poor between 550Mhz-750Mhz

### ISSUE THREAD

**Issue by ariasaki** [F5OEO/rpitx#169]
I have raspberry pi 2 Model B and everything is fine but when I tried to transmit on 600Mhz I realized that the signal is very weak! It's weak at 550Mhz and 750Mhz and when I got closer to 600Mhz I realized it's getting weaker until there is no signal at all.
I know my raspberry pi is not fully compatible but I wanted to know why It's like that?

**Comment by F5OEO** [comment]
Check your antenna ?
