### ISSUE TITLE
rtl_tcp and other tools not working after installing RPiTX.

### ISSUE THREAD

**Issue by mmikheev63** [F5OEO/rpitx#170]
(sorry for my English)
Sometimes I use my Raspberry Pi for an rtl_tcp server. After I installed the RPiTX and it installed own RTL-SDR libraries, the rtl_tcp shows "symbol lookup error: rtl_tcp: undefined symbol: rtlsdr_set_bias_tee". The same situation with other RTL-SDR tools (rtl_fm,  rtl_adsb...). How can I fix this? Thanks in advance...

**Comment by F5OEO** [comment]
Don't thinks related to rpitx but version of rtl-sdr
