### ISSUE TITLE
Documentation: Bandwidth??????

### ISSUE THREAD

**Issue by 0x5c** [F5OEO/rpitx#171]
Looking at the documentation for this project, I can't find the maximum transmission bandwidth.
Is there one? Is it unknown?

It would be nice if it was present somewhere in the doc, or that it is unknown, if applicable.

**Comment by F5OEO** [comment]
The rate of changing the frequency is max around 250 Khz in I/Q mode. However, frequency could be set to a large range of frequencies.
Modulation mode in DVBS could be however done at 1MSamples due to phase changing method (QPSK).
Yes, yet a lot of documentation to do.
