### ISSUE TITLE
Readme: 750 MHz Is this a typo?

### ISSUE THREAD

**Issue by E3V3A** [F5OEO/rpitx#18]
In the Readme.md usage you say: 

> -f float      frequency to output on GPIO_18 pin 12 in khz : (130 kHz to **750 MHz**),

Is [this](https://github.com/F5OEO/rpitx/blob/master/src/RpiTx.c#L979) a typo or can you actually have that high a frequency? In the BCM2835 manual it is stated that the PWM can be most 125 MHz, given the old document assumption on clock freq etc.

Have anyone actually tested this? 
How does it differ for different devices?

**Comment by F5OEO** [comment]
PWM and PCM could be up to 500MHZ using the right PLL.
With PWM there is a divider by 2 to make a waveform : thus 250MHZ.
When frequency is above 250MHZ, rpitx compute the harmonic needed : for example -f 300000 will output 100MHZ but you could listen to the signal on 100*3=300MHZ

**Comment by F5OEO** [comment]
After https://github.com/F5OEO/rpitx/commit/feb6f4cf3e62f013688671abd5d365b6753baf1e frequency fundamental is now up to 500MHZ

**Comment by E3V3A** [comment]
Alright. Thanks.
