### ISSUE TITLE
Will it work with banana pro board?

### ISSUE THREAD

**Issue by virendera** [F5OEO/rpitx#194]
Banana pro board is raspberry pi clone board but not sure rpitx work with it or not. However, raspberry os also run on banana pro. If somebody did it or running it with this board then tell me how and which pin use for tx on banana pro board.

**Comment by A13xund3r** [comment]
No, at least not now and most likely never will, different SoC.

**Comment by F5OEO** [comment]
No : rpitx is raspberry specific !
