### ISSUE TITLE
Pocsag will not work

### ISSUE THREAD

**Issue by Marv0123** [F5OEO/rpitx#198]
Hello, 
i am trying to write a message to a motorola pager frequency is 162.050 Mhz RIC 0550602, 

I use the command: echo -e "0550602: Testmessage" | sudo ./pocsag -f 162.050e6 -r 512

The pager seems to recognize the signal but will not beep or show anything..

What's wrong?

Yours, Max

**Comment by pyrog** [comment]
Hi,

> I use the command: echo -e "0550602: Testmessage" | sudo ./pocsag -f 162.050e6 -r 512
> 
> The pager seems to recognize the signal but will not beep or show anything..
> 
> 
Try the -i option.

BR,

—
Yves

**Comment by Marv0123** [comment]
no also the i-option will not work... hmm.

**Comment by F5OEO** [comment]
Pocsag protocol and not directly related to rpitx

**Comment by Marv0123** [comment]
Which raspberry model do u use ?


F5OEO <notifications@github.com> schrieb am Di. 3. Nov. 2020 um 17:59:
