### ISSUE TITLE
can't generate file from mp3 to wav to ft

### ISSUE THREAD

**Issue by besbesbechir** [F5OEO/rpitx#2]
I tried many times to create ft file but i get the same problem

root@raspberrypi:~/rpitx# convert -depth 8 img.jpg picture.rgb
root@raspberrypi:~/rpitx# ./pisstv picture.rgb picture.ft
Adding VIS header to audio data.
Done adding VIS header to audio data.
Adding VIS trailer to audio data.
Done adding VIS trailer to audio data.
root@raspberrypi:~/rpitx# sudo ./rpitx -m RF -i picture.ft -f 100000
Failed to read Filein picture.ft
rpitx Version 0.1 compiled Nov  2 2015 (F5OEO Evariste) running on END OF PiTx
root@raspberrypi:~/rpitx# ./pifm el.wav fm.ft
Reading file : el.wav
Sample Rate : 48000
Channels    : 1
----------------------------------------
Writing file : fm.ft
root@raspberrypi:~/rpitx# sudo ./rpitx -m RF -i fm.ft -f 100000 -l
Failed to read Filein fm.ft
rpitx Version 0.1 compiled Nov  2 2015 (F5OEO Evariste) running on END OF PiTx

**Comment by F5OEO** [comment]
Maybe some right issue : you seems to be root. Can you test with normal user ?

**Comment by besbesbechir** [comment]
im always getting failed on reading file 


pi@raspberrypi ~/rpitx $ convert -depth 8 picture.jpg picture.rgb
pi@raspberrypi ~/rpitx $ ./pisstv picture.rgb picture.ft
Adding VIS header to audio data.
Done adding VIS header to audio data.
Adding VIS trailer to audio data.
Done adding VIS trailer to audio data.
pi@raspberrypi ~/rpitx $ sudo ./rpitx -m RF -i picture.ft -f 100000
Failed to read Filein picture.ft
rpitx Version 0.1 compiled Nov  2 2015 (F5OEO Evariste) running on END OF PiTx
pi@raspberrypi ~/rpitx $

**Comment by F5OEO** [comment]
Can you check that picture.ft exists and is not zero size ?

**Comment by F5OEO** [comment]
Any answer ? Else will be closed
