### ISSUE TITLE
pocsag deviation at capcode sending

### ISSUE THREAD

**Issue by geekinsanemx** [F5OEO/rpitx#204]
Hi guys!,

hope everyone is doing great!, I got a time trying to revive and old motorola advisor elite (but looks like more like alpha gold model) anyway, it's from skytel in mx, capcode in back of beeper says 4783424 and I've done alot of attempts to make it work, finally seems I've very near to accomplish with, just that now that I can decode messages send by rpitx seems address capcode sent it's wrong!, some numbers seems work fine always number is 6 or less digits, but in 7 digits some time does not bring anything on the screen or capcode is wrong:

i sent this:
```
root@raspberrypi:/usr/local/src/rpitx# echo -e "4783424:Hellow World!" | ./pocsag -f 929.4100e6 -r 512
Channel 14 CBSize 24006 UsermemSize 12003
Using mbox device /dev/vcio.
816204 Size NUM PAGES 200 PAGE_SIZE 4096
BufferSize 12003 , cb 24006 user 12003
Info:NTP find offset 2932608 freq -7302617 pps=0 ppm=-111.429092
Info:NTP find offset 2932608 freq -7302617 pps=0 ppm=-111.429092
Info:NTP find offset 2932608 freq -7302617 pps=0 ppm=-111.429092
Info:NTP find offset 2932608 freq -7302617 pps=0 ppm=-111.429092
Freq PLL no 5= 464702739
Found PLL solution for frequency 929.4MHz : divider:1 VCO: 1858.8MHz
Use PLL Prediv
Master PLLC Locked
Info:NTP find offset 2932608 freq -7302617 pps=0 ppm=-111.429092
Freq PLL no 6= 500055720
PCM prediv = 239
PCM clk=4086 / 2010
FSK Origin fsel 21200900
FSK burst end Tx
```
and I receive this:

```
POCSAG512: Address:  589120  Function: 3  Alpha:   Hellow World!<LF>

```

if I try different baud rates same stuff with different rate: 
```
POCSAG1200: Address:  589120  Function: 3  Alpha:    Hellow World!<LF><NUL><NUL>
```

I've tested using dev branch, and reverting back #147 but same result, 

beside that to hear this on 929.4125Mhz I had to point to 929.4100e6 but this looks like change every reboot, just I need to tune my pointed address but I'm sure that I'm listening it at 929.4125mhz using NooElec sdr-rtl and decoding with multimon-ng, I really hope you can help me! at least try to figure out what I can do to test it by myself!

thank you so much!

**Comment by VasylSamoilov** [comment]
Capcode 4783424 is not possible for POCSAG. POCSAG cap codes are 21 bits long, allowing for up to 2097152 unique cap codes per radio channel. The cap code is comprised of 18 address bits and 3 frame location bits, and proper address plan in even more complex. Please see POCSAG reference documentation. As for your beeper, whatever this number is - it's not capcode. Build a pager programmer and read or update configuration, and frequency is also should not be taken for granted - you best guess is to look what operator pager was tuned for and look up for this country/operator frequency in the archives.
