### ISSUE TITLE
rpitx with FOSS GSM network systems?

### ISSUE THREAD

**Issue by jjZqzb** [F5OEO/rpitx#208]
Hi all. I want to experiment with free, open source software that allows for the creation of GSM networks - examples of this include OpenBTS, Osmocom and PortableCellNetwork. Because I am new to all of this, I would rather make an SDR transceiver than buy one if that means paying less and in this case it obviously would. I'm not sure I can use rpitx for this sort of thing though. Can I? And if I can, how do I get started?

**Comment by F5OEO** [comment]
rpitx is a minimum sdr transmitter...Don't even think about GSM in a near future !
