### ISSUE TITLE
not able to record frequency in iq file please help..

### ISSUE THREAD

**Issue by yashgupta1262** [F5OEO/rpitx#209]
command i am using ..
rtl_sdr -s 250000 -g 42 -f 433937500 car_remote.iq

error
e.iq
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sampling at 250000 S/s.
Tuned to 433937500 Hz.
Tuner gain set to 42.10 dB.
Failed to open car_remote.iq

its says failed to open car_remote.iq 
please help me to solve thanks in advance...

**Comment by andimik** [comment]
Have you tried `-` (for stdout) instead of the file name?

http://manpages.ubuntu.com/manpages/trusty/man1/rtl_sdr.1.html

**Comment by yashgupta1262** [comment]
rtl_sdr -s 250000 -g 42 -f 433937500 -  @andimik  i make this command its worked but it not save any output file now i am confused how to replay it ... i am using this   sudo ./sendiq -s 250000 -f 433937500 - but it not working please help...
thanku so much for helping sir....

**Comment by andimik** [comment]
Do you have write access in the current folder?

**Comment by F5OEO** [comment]
Not related to rpitx itself.
