### ISSUE TITLE
record without going through menu?

### ISSUE THREAD

**Issue by MACscr** [F5OEO/rpitx#210]
Is there a direct cli option that allows me to simply enter the values like frequency, gain, etc, from the cli and specify the record filename, etc? When you have a bunch of recordings to do with similar values, its kind of cumbersome to go through the rtlmenu.sh

**Comment by MACscr** [comment]
Looks like ```rtl_sdr -s 250000 -g 35 -f 433.969e6 outlet_1_on.iq``` will do it?

**Comment by F5OEO** [comment]
Inspect test scripts for inspiration.
