### ISSUE TITLE
RPITX ./rtlmenu.sh record and play doesn't work

### ISSUE THREAD

**Issue by pun92** [F5OEO/rpitx#211]
Hi... recently i install RPITX and the part of that include RECORD and PLAY doesn't work... it worked before for me but i don't know what's happen to it...its record signal but its sends a vague signal when its played also i'm not be able to record signal with rtl_sdr command ??? can you help me in this case guys thanks.

**Comment by F5OEO** [comment]
Not directly related to rpitx
