### ISSUE TITLE
Compile failure on csdr?

### ISSUE THREAD

**Issue by dachshund-digital** [F5OEO/rpitx#213]
Compile failure on csdr?

gcc -std=gnu99 -O3 -ffast-math -fdump-tree-vect-details -dumpbase dumpvect -mfloat-abi=hard -mcpu=arm1176jzf-s -mfpu=vfp -funsafe-math-optimizations -Wformat=0 fft_fftw.c libcsdr_wrapper.c  -g -lm -lrt -lfftw3f -DUSE_FFTW -DLIBCSDR_GPL -DUSE_IMA_ADPCM -Wno-unused-result -fpic -shared -Wl,-soname,libcsdr.so.0.15 -o libcsdr.so.0.15

In file included from fft_fftw.c:3:
fft_fftw.h:7:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.

**Comment by F5OEO** [comment]
Seems package libfftw3 was not installed.
