### ISSUE TITLE
Not transmitting on pi2 or pi3 with raspian stretch

### ISSUE THREAD

**Issue by 2fatninja** [F5OEO/rpitx#222]
I’ve tried both a pi2 and pi3 and neither seem to be generating a signal off of GPIO 4 with easytest.

I’ve tried walking the pins and can’t find a hint of a signal when doing the carrier test - did something recently break or is there another raspian version other than the last 2019 lite release I should be using?

**Comment by F5OEO** [comment]
should be fixed as generation was broken see #220
