### ISSUE TITLE
Well, as of the last set of updates to Buster (Debian 10) on Raspberry Pi, my last Pi3 crashes if I attempt to run sendiq

### ISSUE THREAD

**Issue by dachshund-digital** [F5OEO/rpitx#226]
Well, as of the last set of updates to Buster (Debian 10) on Raspberry Pi, my last Pi 3 crashes if I attempt to run sendiq.  So RPiTx I guess is finally completely dead?  It stopped working on Pi Zero, Pi Zero W, my last Pi 2, and now all of my Pi 3 devices.  Never was able to get it to work on any Pi 4 on Buster.  R.I.P. RpiTx.

**Comment by F5OEO** [comment]
Pi4 is in beta..Rpitx still alive !

**Comment by Nodi-Rubrum** [comment]
Oh, man!  That is really great to hear!
