### ISSUE TITLE
Strange timing problems

### ISSUE THREAD

**Issue by clemibunge** [F5OEO/rpitx#227]
Well, the problem is that everything is sped up -> example video( https://imgur.com/a/SrILgKu ) even POCSAG and opera and SSTV so it doesn't seem to be related to any sample rate issues but rather to some timing library I don't know... I guess some library that is installed via APT changed something...
So I just installed Rpitx on my RPI 3B and it had the described timing issues tried a second board cuz I thought it was faulty.. it wasn't ... Tried a raspberry pi zero with had the same issues... I did a clean install of Raspian stretch every time and installed nothing else just rpitx

**Comment by F5OEO** [comment]
I am working on release the pi4 version, but did a wrong testing before commit to master ! The version is unstable at the moment.

**Comment by F5OEO** [comment]
Should be fixed ! Can you try to reinstall to confirm it is working at proper speed ?

**Comment by clemibunge** [comment]
I'll test it in two hours still in school right now

**Comment by clemibunge** [comment]
the timing works now! but the frequency is kinda inaccurate by ~5Khz

**Comment by F5OEO** [comment]
Have your raspberry an internet connexion (for ntp)?

**Comment by clemibunge** [comment]
I do have an internet connection for the RPI's yes
I tried transmitting on 446.006Mhz with the pi zero and the frequency was off by -8Khz
on the pi 3, the frequency is off by about +2Khz  I guess that's normal?

**Comment by clemibunge** [comment]
ah and btw u disabled dvbrf right? you forgot to remove it from the makefile i got an not found error while installing

**Comment by F5OEO** [comment]
Sure ? https://github.com/F5OEO/rpitx/commit/d1d8a37f95b5f061f3656dddb80e7cfd0a1916ff

**Comment by clemibunge** [comment]
yes, sure look at line 101

**Comment by clemibunge** [comment]
frequency got more stable now(~0.5khz off) NTP did its job 

closing the issue
