### ISSUE TITLE
RPI 3 ...transmission start and stop, then restart..fake colors on sstv

### ISSUE THREAD

**Issue by michelinok** [F5OEO/rpitx#24]
Hi,
I own only a raspberry 3 and i've noticed these problem (i think it's something on my setup since it works for you...)
- The transmission of sstv start and stop randomly during a transmission
- The colors are not the same of the original image (tryed the raspberry cam and an user provided image).
- Does it transmit as Martin 2 mode?

Any idea?

**Comment by F5OEO** [comment]
With Rpi3 there is CPU save mode which break intermitently the transmission. The easiest way is to set  force_turbo=1 in /boot/config.txt
About SSTV, I just put it as a test and other mode could be easily implemented. As I remember the mode is Martin 1.

**Comment by michelinok** [comment]
Quite strange...enabling turbo it doesn't transmit anything, reverting to non-turbo it transmit (but of course same problem as before)
Any idea?

**Comment by F5OEO** [comment]
disable_pvt=1
force_turbo=1
arm_freq=700
gpu_freq=250
core_freq=250
sdram_freq=400

Is my configuration ... Have to check really on Rpi3 !

2016-07-01 20:39 GMT+02:00 michelinok <notifications@github.com>:

**Comment by jnk0le** [comment]
The problem is frequency of PLLC (used by rpitx), which drifts with overclock.

**Comment by michelinok** [comment]
F5OEO, that's exactly my config :(

**Comment by michelinok** [comment]
Ok,,,just tryed on raspberry 1....it doesn't start/stop randomly, but images are totally wrong, cannot see anything related to the original image (tryed  with raspicam too...)
Can someone send me a .ts image to test? maybe that's the problem...

**Comment by jnk0le** [comment]
Have you tried other modes? How does 100MHz FM carrier looks like ?

**Comment by michelinok** [comment]
Sorry for the big delay...my rx was k.o....
Other modes are ok, no way to see the 100MHz because i can do only 0-30Mhz :°(
Any idea? I really really would like to enjoy sstv.

**Comment by michelinok** [comment]
any idea?

**Comment by F5OEO** [comment]
Shoud be fixed with https://github.com/F5OEO/rpitx/commit/feb6f4cf3e62f013688671abd5d365b6753baf1e

**Comment by michelinok** [comment]
Going to try sooooooon (does it works with rpi 1?)

Il 27 ago 2016 15:38, "F5OEO" <notifications@github.com> ha scritto:

**Comment by F5OEO** [comment]
Not tested with rpi1 (all mines burnt) but theorical work (quiet same as Pizero which work)
