### ISSUE TITLE
Tested on RPi 3 B Raspbian Buster and Raspbian Stretch And .....

### ISSUE THREAD

**Issue by Ghaz75** [F5OEO/rpitx#249]
The main culprit is the parameter force_turbo=1 with default 1. I had this value in /boot/config.txt along with gpu_freq=250. In my Raspbian Stretch With Desktop OS I made sure that there is no over clocking. I left the gpu_freq=250 and changed the force_turbo=1 to 0 and gave a reboot. And Voila. 
But for AM mode the voice is like chipmunks. Rest all modes are working fine.
For Raspbian Buster try force_turbo=0, so far I have no success on raspbian buster. 
Thanks.

**Comment by F5OEO** [comment]
OS next check update
