### ISSUE TITLE
Change default pin

### ISSUE THREAD

**Issue by michelinok** [F5OEO/rpitx#25]
How can i change the default pin from GPIO18 to GPIO4 ?
Many thanks

(a command line switch would be a suggestion...)

**Comment by F5OEO** [comment]
Using an undocumented option : -c 1

**Comment by michelinok** [comment]
thanks, seems to work fine

**Comment by jbdu94** [comment]
And can we change to another pin? Example pin 32

**Comment by jemussi** [comment]
-c 1 not working at all for me giving error messages. Could you give a full usage example please?
