### ISSUE TITLE
librpitx

### ISSUE THREAD

**Issue by ha7ilm** [F5OEO/rpitx#28]
If `rpitx` was split into a library that provides C API, and command-line tools that link to the library, then it was possible to build other apps on it. E.g. one could easily add `rpitx` support to SoapySDR or gr-osmosdr.

**Comment by F5OEO** [comment]
Yes, agree ! Have you idea of what functions to expose which could be
required to be as simple as possible to be integrated (SoapySDR,
GnuRadio...)?

**Comment by F5OEO** [comment]
Fixed in V2 !!!!
