### ISSUE TITLE
what type of wire do i put on the pin?

### ISSUE THREAD

**Issue by ItsYXT** [F5OEO/rpitx#283]
what type of wire do i use

**Comment by ppoojohn** [comment]
Any wire just something conductive 
As far as I know

**Comment by ItsYXT** [comment]
how do you put a wire on those type of pins? What type of wire?

**Comment by ppoojohn** [comment]
I use a aluminum wire and tie it around the pin

**Comment by ItsYXT** [comment]
oh how thick is the wire, if you know?

**Comment by ppoojohn** [comment]
About 22 - 26 Guage wire

**Comment by ItsYXT** [comment]
okay, thank you!

**Comment by alexmyczko** [comment]
@ItsYXT i guess you can close this issue now?
