### ISSUE TITLE
Glitchy output on RaspPi 3 and 1 without `-c 1`

### ISSUE THREAD

**Issue by natevw** [F5OEO/rpitx#29]
When I do `sudo ./rpitx -m VFO -f 1000` is it right to expect basically a square wave at 1000 kHz?

Instead, I get really sporadic pulses, as shown in [this video](https://twitter.com/natevw/status/763233882841817088).

Is this some sort of Pulse-Density Modulation trick or similar, or is something wrong? Mostly just trying to wrap my head around this. I am able to hear the FM sample via a broadcast receiver but when I lower the frequencies to what my 100MHz scope is supposed to be able to pick up, I don't see what I would expect.

**Comment by natevw** [comment]
After trying just the `disable_pvt=1` by itself, I tried adding all the settings recommended in https://github.com/F5OEO/rpitx/issues/24#issuecomment-230030147. Still pretty much the same behavior, maybe a tiny bit better but could be my imagination.

Interestingly, after changing the settings when I run `vcgencmd get_config disable_pvt` it says "disable_pvt is unknown"! The other settings from #24 discussion are shown, e.g. it shows me that "force_turbo=1" and the freq settings as expected. But *not* `disable_pvt`.

I found https://github.com/raspberrypi/firmware/commit/ac0c0bff7951a39d371a46c4a80a9ec560e33c16 which commit message says this option might be removed?

**Comment by natevw** [comment]
The VFO mode actual seems to produce a nice square wave for frequencies between about 2.5 kHz and 500 kHz. Somewhere above there, the glitches start getting worse and worse.

I wouldn't rule it completely out, but I don't think this is just a triggering/scale artifact on my oscilloscope. I can leave the horizontal scale the same between 500 kHz and 800 kHz. At 500 kHz it's not "rock solid" but it's pretty good. At 800 kHz the glitching is very apparent.

I'll share a video via Twitter again and update this when it's posted.

**Comment by natevw** [comment]
I tried my card in a Raspberry Pi 1 — same things! (I did do `make clean` in src and rebuild just in case, but didn't help either.)

So I ran git bisect.

![screen shot 2016-08-10 at 11 04 00 pm](https://cloud.githubusercontent.com/assets/265902/17579977/680c8952-5f4f-11e6-926e-a997172596d5.png)

After https://github.com/F5OEO/rpitx/commit/f34233268f384aaec8005196c4bffa501a7ea637 was applied, I start seeing the "glitches" at e.g. 27125 kHz VFO output, and FM transmit at 103300 gets very very distorted. If I checkout https://github.com/F5OEO/rpitx/commit/a274a8f18969248f417f0224b540874215caf8d0 immediately before the "Add GPCLK output" commit, then the output FM example at 103300 it is actually fairly clean in the local spectrum!

**Comment by natevw** [comment]
As suggested [via Twitter](https://twitter.com/F5OEOEvariste/status/763633530366812160), I tried sending the signal to GPIO 04 (pin 7) by adding the `-c 1` option on the latest master currently ca94b38c1ad72a5d281dd26c0a0e3d8cf75588bd. This actually looks really good, even compared to  a274a8f!

![screen shot 2016-08-11 at 9 58 00 pm](https://cloud.githubusercontent.com/assets/265902/17613374/568fd18a-6011-11e6-99b9-c2fbbd1463fb.png)

It's certainly not perfectly clean on the RTL-SDR "spectrogram" but looks the best I've seen it yet, from 5 kHz on up, when viewed on the oscilloscope. I'm not sure exactly what this option does (okay — I still am quite fuzzy on how the original PE1NNZ prototype even works :-) but it seems to be the right one right now!

**Comment by freebil** [comment]
Hello. I tried sudo ./rpitx -m VFO -f 1000 and I take nice square waves without glitches

![ds1z_quickprint3](https://cloud.githubusercontent.com/assets/18070734/17862855/c896d04e-689f-11e6-8771-00bc17fb2f5e.png)

**Comment by F5OEO** [comment]
@freebil raspberry model , Linux version ?

**Comment by freebil** [comment]
@F5OEO Raspberry pi 3 with the latest raspbian jessie lite.
