### ISSUE TITLE
How To Send Data and Image using rpitx?

### ISSUE THREAD

**Issue by nau4k** [F5OEO/rpitx#294]
Hello everyone, I have a project from my lecturer. this project uses Raspberry pi 3b+ and RTL-SDR. Raspberry using rpitx to transmit RF signal.
The expected result is that raspberry can send data and images via Radio Frequency and received with rtl sdr with gnu radio. Hopefully anyone can teach me i will be very grateful

**Comment by radiocolin** [comment]
So you want someone else to do your project?

**Comment by nau4k** [comment]
> So you want someone else to do your project?

I'm not sure about that, I just want to know what to use to do the project

**Comment by nau4k** [comment]
> So you want someone else to do your project?

I'm not sure about that, I just want to know what to use to do the project

**Comment by Lucstay11** [comment]
> Hello everyone, I have a project from my lecturer. this project uses Raspberry pi 3b+ and RTL-SDR. Raspberry using rpitx to transmit RF signal.
> The expected result is that raspberry can send data and images via Radio Frequency and received with rtl sdr with gnu radio. Hopefully anyone can teach me i will be very grateful

A can do it for you!

**Comment by nau4k** [comment]
> > Hello everyone, I have a project from my lecturer. this project uses Raspberry pi 3b+ and RTL-SDR. Raspberry using rpitx to transmit RF signal.
> > The expected result is that raspberry can send data and images via Radio Frequency and received with rtl sdr with gnu radio. Hopefully anyone can teach me i will be very grateful
> 
> A can do it for you!

can you teachme please?

**Comment by Lucstay11** [comment]
Use the 5th option of rptix you can send images via SSTV.
_If that's just what you want to do, it's not very complicated_

**Comment by mattvall1** [comment]
> Hello everyone, I have a project from my lecturer. this project uses Raspberry pi 3b+ and RTL-SDR. Raspberry using rpitx to transmit RF signal. The expected result is that raspberry can send data and images via Radio Frequency and received with rtl sdr with gnu radio. Hopefully anyone can teach me i will be very grateful

Completely out of interest, what degree are you studying for. That sounds very cool!
