### ISSUE TITLE
Where is SendOOK.sh?

### ISSUE THREAD

**Issue by petitxef** [F5OEO/rpitx#310]
I've installed in a fresh Raspberry pi 3+ following the instruction, but I can not find the "sendook.sh" function.

What I'm missing?
Thanks!

**Comment by shortgame11** [comment]
What was the solution?

**Comment by petitxef** [comment]
> What was the solution?

[Here](https://github.com/F5OEO/rpitx/issues/311#issuecomment-1854611276)
