### ISSUE TITLE
More dead projects?

### ISSUE THREAD

**Issue by sysadminpower2019** [F5OEO/rpitx#317]
It seems a lot of projects have been inactive for years when they could really benefit many people.

**Comment by vrdriver** [comment]
That's why I tend to look at how many times a project has been forked or cloned to see where the most recent version is and what changes have been made.
https://github.com/F5OEO/rpitx/network

**Comment by F5OEO** [comment]
Projects are maintained by volunteer...Time could not be extended, so some priorities happen...as soon as the project still working, not always needed to update it.
