### ISSUE TITLE
rpitx library

### ISSUE THREAD

**Issue by F5OEO** [F5OEO/rpitx#33]
Make a lib-rpitx for external software build. 
Need to write exposed functions. 
Requirement and proposals welcomed.

**Comment by michelinok** [comment]
a gnu radio companion tx block would be the greatest thing i think :)

**Comment by ha7ilm** [comment]
@michelinok You can already TX with GNU Radio, as [detailed here](https://github.com/ha7ilm/rpitx-app-note), although it was nicer to have a dedicated block.

**Comment by F5OEO** [comment]
Agree for GnuRadio sink block. However, suprisely, I never wrote a gnuradio block. So help or sample will be needed to developp ( @ha7ilm ) !
