### ISSUE TITLE
Please include a warning: This may not be legal where YOU live.

### ISSUE THREAD

**Issue by SlySven** [F5OEO/rpitx#44]
In some legislative areas of the World transmission systems have to be designed and approved to certain standards and may require licensing to broadcast (transmit) even low power signals and only operate in certain frequency bands.

I don't want to be a party-pooper but please include a warning for potential users (on the front page in the README.md perhaps) to check that they can use their RPi for this purpose where they are.  If they cannot they may just forfeit their kit if they are lucky; if they are not, they may receive not just a strong _signal_ but a much more _personal_ interaction from their country's legislative arm of Government. :grimacing:

**Comment by F5OEO** [comment]
Fixed with a "copy/paste" of the well known HackRF.
https://github.com/F5OEO/rpitx/commit/bfa34477316e357529b9e9005cb680964f7db429
