### ISSUE TITLE
Rpi A+

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [F5OEO/rpitx#5]
Hi, thanks for sharing this great project!
I discover that it officially doesn't have support for the A+ model. Why is that? because of memory? do you think there is going to be A+ version working on the future?

Thanks again and congratulations for the good work.

Patricio

**Comment by F5OEO** [comment]
A+ should work, but not have a unit to test

**Comment by patriciogonzalezvivo** [comment]
Hi! I tested and it doesn't seams to work. The program finish before sending anything. I will test again giving more memory to the CPU.

**Comment by patriciogonzalezvivo** [comment]
This is what I get on my A+

```bash
$ ./snapsstv.sh                                                                                                                                                                                                   *[master]  
Adding VIS header to audio data.
Done adding VIS header to audio data.
Adding VIS trailer to audio data.
Done adding VIS trailer to audio data.
rpitx Version 0.1 compiled Nov 14 2015 (F5OEO Evariste) running on  Model Pi 2
Resolution(Hz)=18.366667
END OF PiTx
```

 
<img width="880" alt="screen shot 2015-11-24 at 3 23 09 am" src="https://cloud.githubusercontent.com/assets/346914/11361341/e9383372-925a-11e5-9ad9-5e0cc19aec64.png">

**Comment by ha7ilm** [comment]
Hi!
It seems to me that `piBoardId` identifies this board as Pi 2 erroneously.
Could you post the output of `cat /proc/cpuinfo` on the A+?

**Comment by ha7ilm** [comment]
You could also try this temporary modification whether it fixes your problem:

Replace this line over here:

https://github.com/F5OEO/rpitx/blob/master/src/RpiGpio.c#L17

...with the following:

    if(false)

**Comment by patriciogonzalezvivo** [comment]
Hi! Thanks for the answer and temporal fix.
Here is the ```/proc/cpuinfo```

```bash
[~]$ cat /proc/cpuinfo                                                                                                                 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 2.00
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 0012
Serial		: 000000009ae35ba7
```

**Comment by ha7ilm** [comment]
Thanks. I'm going to make a test with it as soon as I have time.

Did the temporary fix work?

**Comment by patriciogonzalezvivo** [comment]
Yes! it compiles and sends something that I can catch with my rtl_sdr. ( I'm sending images trough sstv script - great work btw!! Still need to learn how to capture it back : ) )

Thanks!

**Comment by tomswartz07** [comment]
@patriciogonzalezvivo to capture it back, you'd be well suited to use a RTL-SDR; which is a modified USB tv tuner that can capture a wide range of radio frequencies. You can find them for about $12 on Amazon.
:radio: 

My personal setup has [this SDR](http://www.amazon.com/RTL2832U-Low-Cost-Software-Compatible-Packages/dp/B00SXZDUAQ/ref=sr_1_4?ie=UTF8&qid=1449060125&sr=8-4&keywords=rtl+sdr) and I use the program GQRX on my laptop to view the radio freqencies.

Hope this helps!

**Comment by F5OEO** [comment]
Model detection should be fixed : https://github.com/F5OEO/rpitx/commit/feb6f4cf3e62f013688671abd5d365b6753baf1e
