### ISSUE TITLE
IQ samples from TCP/UDP 

### ISSUE THREAD

**Issue by bssstudio** [F5OEO/rpitx#53]
I would just like to discuss if it would be possible to extend the input options to allow receiving raw/float IQ samples from the network (using either TCP or UDP socket). That would extend the usability of this project as one could then prepare the TX chain in (for example) GNU Radio and output it to the RPiTX to transmit via network.

Comments greatly appreciated.

**Comment by F5OEO** [comment]
Yes, rpitx will be based on a  library soon : thus could be inserted in SoapySDR or Gnuradio. IP could be added more easy then. For now it could already be done but not directly (see notes from HA7ILM). I mainly work on rpidatv for now, but back soon to improve rpitx. Thanks for supporting it !

**Comment by ha7ilm** [comment]
@bssstudio see: https://github.com/ha7ilm/rpitx-app-note
