### ISSUE TITLE
Terrible audio in AM, also PiFmRds won't work if you install it!

### ISSUE THREAD

**Issue by pilovis** [F5OEO/rpitx#60]
Very bad program!
The AM modulation is so awful.
I'm trying to understand how to recover my fantastic PiFmRds :(

**Comment by pilovis** [comment]
Weak programmers do not write instructions how to uninstall their programs.

To remove rpitx and to get PiFmRds working again, follow these steps:

rm /boot/dt-blob.bin
rm /usr/bin/pifm
rm /usr/bin/piam
rm /usr/bin/pisstv
rm /usr/bin/pissb
rm /usr/bin/pifsq
rm /usr/bin/rpitx

then go to "PiFmRds/src" and run "make clean" and "make" to reinstall PiFmRds, then reboot.

**Comment by nexus166** [comment]
pro users make backups

**Comment by pilovis** [comment]
The worst is that  "/boot/dt-blob.bin" changes the default pin configurations of your Raspberry (persistent modification after reboot)!

At least he should have warned us before starting the installation of this program.

**Comment by F5OEO** [comment]
Warning : Read the GPL Licence :

> This program is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU General Public License for more details.
