### ISSUE TITLE
pissb    Input rate must be 48K.

### ISSUE THREAD

**Issue by SnkMtn000** [F5OEO/rpitx#61]
Converted a capture file to 48K mono audio file using audacity.  Tried saving at all bit rates.  Regardless I see the message, "Input rate must be 48K".  What am I missing?  Thanks.

**Comment by SnkMtn000** [comment]
Simple
sudo apt-get install sox
sox infile.wav -c 1 -r 48000 outfile.wav
done!

**Comment by F5OEO** [comment]
Easy and quick solution .. need to note it on readme !

**Comment by SnkMtn000** [comment]
I say into the pi from work.  Want to test the broadcast of psk31 when I
get home.
