### ISSUE TITLE
DCF77 antenna

### ISSUE THREAD

**Issue by edxk** [F5OEO/rpitx#63]
Prompt please, for transmission of DCF77 some special antenna is necessary?
Or the piece of a wire approaches?
Just I connected a piece of a wire, but hours aren't set up and don't see a signal.

But also I noted that in case of start of FM on receivers there are noises.

**Comment by gaionim** [comment]
For me was the clock; 
My clock is not listening everytime, I must turn off and turn on the radio before to transmit.
I use  1 meter long wire .

**Comment by emard** [comment]
I did resonant series LC circuit at 77.5kHz directly across gpio pi and gnd. L on ferrite, C 1-5 nF choose value that works best Can produce 15-20V at L. Also can damage the gpio pin.
