### ISSUE TITLE
rpitx power out & tcp socket freq change

### ISSUE THREAD

**Issue by anggafunkadelic** [F5OEO/rpitx#70]
What is the actual impdance & output power of rpitx ?
is there any planning to add frequency replacement feature when running through tcp socket like gqrx ?

This is my experiment measuring power with ad8307 powermeter (DIY) https://www.youtube.com/watch?v=juT-2LdAdYg

Thanks

YD1GPW

**Comment by F5OEO** [comment]
Hi ,

Made some tests and impedance is an interesting parameter to know. If we modulate at constant level (FM,PSK,VFO..) impedance should be 3.3v/16ma : around 200 ohm. But as rpitx use gain control to modulate in amplitude, the minimum gain is 2ma thus : 3,3/2=1,6Kohm.
Best should be to have a high impedance amplifier to allows to convert to 50 ohms: hope that there could be some hardware contribution for performing that.

Using a VNA could maybe be more precise to know impedance against frequency and gain.

Thx for your measurements.

About changing frequency from external software , I begin to write a SoapySDR driver.
