### ISSUE TITLE
Modulate pll instead clock divider leads to a pure signal

### ISSUE THREAD

**Issue by ghost** [F5OEO/rpitx#75]
Is it technically possible to implement this commit from a fork of PiFmRds to Rpitx ?
[](url)
https://github.com/SaucySoliton/PiFmRds/commit/6984fd64b7d919f7632850f6c66826880daeef00

The result of pll modulation is just amazing. Only harmonics emissions, no more spurious, heavy intermod, phase noise...
Bonus, carrier can go up to 650MHz, rpitx is limited to 250 before switching to harmonic mode.
With it, the RF output looks almost like a regular transmitter and is not scary anymore. 

Thank you for your amazing work.

**Comment by F5OEO** [comment]
Thx very much for pointing this commit : I used this by device tree but that's only for one time. I was inspecting the source code from driver but didn't make this amazing work to port it to userland. 
I will try to include it on rpitx...just wonder if PLL is enough fast to modulate at high bandwidth.

**Comment by samirbonnet** [comment]
Thanks, for people who didnt follow the story from the beginning. (pifm then dma then iq mixing emulation)
Creating a development guide, high lvl design or a block diagram will allow you to outsource this kind of work, the creation of a rpitx dev team or even for education purposes !

In IQ Transmitters RF output is achieved by summing two carrier I*cos(wc) and Q*sin(wc) which means hidden in rpitx code there should be 3 amplitude controllers.

1 for summing I*cos(wc) and Q*sin(wc)        result (I*cos(wc)+Q*sin(wc)) >>> direct-RF yay
1 to control amplitude of cos carrier              result I*cos(wc)
1 to control amplitude of sin carrier               result Q*sin(wc)

And obviously rpitx works, as I got no issues Txing some strange/beautiful continuous-phase PSK modulations with it... can you tell us how do you manage to get such amazing result with only frequency control.

**Comment by samirbonnet** [comment]
Of course if making pdf is not your thing, I can do the work for you, good documentation will ever be better than exhaustive comments in source code. Creating an IQ mixer with just a square generator as a lot of applications. If you want feel free to contact me in french.

**Comment by F5OEO** [comment]
You can contact via email.

**Comment by F5OEO** [comment]
Thx again as this is the beginning of the librpitx and V2 version
