### ISSUE TITLE
Cant boot with dt-blob.bin

### ISSUE THREAD

**Issue by newperson1746** [F5OEO/rpitx#79]
I have a Raspberry pi 3 v1.2 and as part of the install steps it copies dt-blob.bin to the /boot folder. (This is for the gpio assignments I believe) On the next reboot, the raspberry pi just stops booting and blinks 7 times (kernel.img not found) upon removing dt-blob.bin the pi immediately begins to boot successfully. What's wrong? I tried compiling my own from the dt-blob.dts in the src/ folder but to no avail. What's happening? Raspbian jessie, usb boot. All updates installed.

**Comment by F5OEO** [comment]
Need to check with latest version of jessie. Will be back on September to release new version. In the meantime you could check Dev branch
