### ISSUE TITLE
setTime.py not transmitting anything

### ISSUE THREAD

**Issue by antonioag95** [F5OEO/rpitx#80]
I'm trying to use rpitx to transmit DCF77 signal to my radio controlled clock as soon as where I live the signal barely arrives, but the script is not transmitting anything, no signal is received by the clock.
I'm trying it with a simple wire on GPIO18 on my Raspberry Pi 3. This is my Raspbian version generated with the command uname -a:

    Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

**Comment by febalci** [comment]
Well tried both master and dev branches on 3 different DCF clocks with both pins 12 and 7. I'm on rPi3B Jessie; and i also couldn't managed to set the time.
