### ISSUE TITLE
How to tx no modulation signal?

### ISSUE THREAD

**Issue by grinderblade** [F5OEO/rpitx#83]
Hi. I trying tuning IF in my receiver and need HF generator tuning on 10.7 mhz. Signal must be nomod. How I can use ur program for my goal?

In additional. I found some problem with transmit on rpi 3. After starting a tx, signal have distortions and after few moments signal is disappear.

**Comment by F5OEO** [comment]
You can use VFO mode : 
sudo ./rpitx -m VFO -f 10700 -a 14 -c 1

(with this command it should run on rpi3 and output pin is GPIO 4 : pin 7 of header)

**Comment by grinderblade** [comment]
Big thx. `-a 14` that what i need. no more disappear of signal. Now i can tuning detector)
