### ISSUE TITLE
usage in cubesats

### ISSUE THREAD

**Issue by rnbokade** [F5OEO/rpitx#89]
can this be used with some good filter and an amplifier circuit to use with lower earth orbit cubesat

**Comment by cipiricus** [comment]
If you want to use Raspberry Pi as main board in a cubesat will be useless, because if i'm not wrong all satellites use a special radiation hardened electronics which are very expensive, Raspberry Pi is not designed for that purpose

**Comment by ha7ilm** [comment]
Power efficiency is also questionable if using it on-board.

I guess @rnbokade would rather use it from the ground to communicate with a cubesat, right?

**Comment by lu9cbl** [comment]
You can use the raspberry py CM3 (Computer Module 3), that it's designed to special enviroments. Maybe it's works in a Cubesat.
