### ISSUE TITLE
Quits in Putty

### ISSUE THREAD

**Issue by Commander-Crash** [F5OEO/rpitx#98]
Hi I am wondering if there is a way to make it so rpitx will not quit if terminal window is moved. When running rpitx if the terminal like putty or android's connect bot is moved in anyway like resizing or if the on screen keyboard comes up then rpitx will quit even with the "-l" command. I don't know if its a issue to most but on android I cant keep my screen on all the time And would like to check on it sometimes with out it quitting. Thanks.

**Comment by OrbitTheSun** [comment]
Maybe you can use the session manager **screen**. This keeps the terminal sessions alive, even when Putty is closed.

`sudo apt-get install screen`

A very useful utility!

-Andreas

**Comment by Commander-Crash** [comment]
OrbitTheSun Thanks for the advice _ will give it a try_
